### ISSUE TITLE
No line numbers

### ISSUE THREAD

**Issue by magical-heyrovsky** [FelisDiligens/joplin-plugin-cmoptions#1]
[Screencast from 2023-02-12 17-47-31.webm](https://user-images.githubusercontent.com/101060148/218324775-03168b0d-0b3c-4b9e-95fd-f7c189ec0257.webm)

Joplin 2.9.17

**Comment by magical-heyrovsky** [comment]
Ah, I just realized that the line numbers are probably only visible in the markdown editor?

**Comment by FelisDiligens** [comment]
Hi @magical-heyrovsky,
yes, it's only visible in the markdown editor ([CodeMirror](https://codemirror.net/)). The WYSIWYG editor is a different editor ([TinyMCE](https://www.tiny.cloud/)).
I'm not sure whether TinyMCE supports displaying line numbers. Might be worth researching.
