### ISSUE TITLE
Relative line numbers

### ISSUE THREAD

**Issue by Opisek** [FelisDiligens/joplin-plugin-cmoptions#2]
Would it be possible to add an option to make the line numbers relative? Assuming In the following example that I'm at line 5, it would look like this:
```
1 Example
2
3 Normal line numbers
4
5 I'm here right now
6
7
```

```
  4 Example
  3
  2 Relative line numbers
  1
5   I'm here right now
  1
  2
```

If you feel like this would be a nice addition but prefer not to implement it yourself, I could look into opening a pull request.

**Comment by FelisDiligens** [comment]
Joplin uses [CodeMirror 5](https://codemirror.net/5/). (5.65.9)
There's a closed issue with relevant code, that I found here: https://github.com/codemirror/codemirror5/issues/4116
Perhaps we could start with that? I'm busy at the moment, so if you want to take a shot at it, I'd be happy to merge a PR.

**Comment by FelisDiligens** [comment]
I added relative line numbers in v1.1.0

![](https://github.com/FelisDiligens/joplin-plugin-cmoptions/assets/47528453/ee5b3c61-1633-4321-ac7b-121573fcdf9d)
![](https://github.com/FelisDiligens/joplin-plugin-cmoptions/raw/main/assets/relative_line_numbers.png)

**Comment by Opisek** [comment]
Works great, thanks a lot!
