### ISSUE TITLE
Line numbers drawn over text

### ISSUE THREAD

**Issue by AZ2Tonez** [FelisDiligens/joplin-plugin-cmoptions#3]
I'm seeing an issue where with line numbers enabled and viewing in dual-pane mirror edit mode with note list and notebook list panels enabled the line numbers background renders over the top of the text and the numbers are not aligned with it. If I turn off one or the other of the note/notebook list panels or use single-pane edit mode, everything looks correct. Attaching screenshots to show what I mean. FWIW, I disabled all other plugins and confirmed the same behavior.

Bug
![image](https://github.com/FelisDiligens/joplin-plugin-cmoptions/assets/2982767/74dee96f-e263-4e5e-bfdf-c40db07273bd)

OK
![image](https://github.com/FelisDiligens/joplin-plugin-cmoptions/assets/2982767/850da8a0-59ea-4b0e-8cc4-f5e858349693)
![image](https://github.com/FelisDiligens/joplin-plugin-cmoptions/assets/2982767/e89f4172-11d4-4eee-83df-121650be813a)
![image](https://github.com/FelisDiligens/joplin-plugin-cmoptions/assets/2982767/8c506fd1-bf23-45e6-8502-7302488a8bd9)

**Comment by AZ2Tonez** [comment]
After further investigation, it looks like it is solely related to displaying the note list panel. Because showing that and not the notebook panel is also slightly broken, but showing just the notebook panel, it's ok.

![image](https://github.com/FelisDiligens/joplin-plugin-cmoptions/assets/2982767/4f2655a7-b540-4d3e-aca3-154ef57ffebe)
![image](https://github.com/FelisDiligens/joplin-plugin-cmoptions/assets/2982767/39883087-f50a-4e5f-a9a5-fbef816b7d21)

**Comment by AZ2Tonez** [comment]
It looks like it may have to do with the size of the panels - if I just show the notebook panel and slowly increase its width, you can see how the numbers/brown background shift where they move to the left and are eventually hidden and the brown background moves further to the right and covers more and more of the text.

![image](https://github.com/FelisDiligens/joplin-plugin-cmoptions/assets/2982767/096e3f9d-4052-48a7-92f9-9a30b331fc55)
![image](https://github.com/FelisDiligens/joplin-plugin-cmoptions/assets/2982767/25d664fd-7409-4659-a8bd-4511527598ed)
![image](https://github.com/FelisDiligens/joplin-plugin-cmoptions/assets/2982767/afb0fde7-6e38-4bb4-8aa4-12912cac9b4f)
![image](https://github.com/FelisDiligens/joplin-plugin-cmoptions/assets/2982767/7f67bafd-38e8-4b44-8cc8-5f5ecac43dc4)

**Comment by FelisDiligens** [comment]
Hm, this is weird, I can't replicate this bug. I tried resizing it and toggling panels. Not sure what's going on...  
It looks like a CSS/styling issue. Do you perhaps use custom stylesheets (`C:\Users\yourname\.config\joplin-desktop\userchrome.css`)?

<details>
<summary>Screenshots (Click to expand)</summary><br>

With line wrapping:
![Screenshot_20230730_224900](https://github.com/FelisDiligens/joplin-plugin-cmoptions/assets/47528453/cf154a22-4c93-4405-ab8f-e3406585db3c)

Without line wrapping:
![Screenshot_20230730_224924](https://github.com/FelisDiligens/joplin-plugin-cmoptions/assets/47528453/705c21c1-42d4-4a3c-b875-8eff5cc730c5)

</details>

**Comment by AZ2Tonez** [comment]
Yea, that is weird... FWIW, I don't use custom stylesheets:
![image](https://github.com/FelisDiligens/joplin-plugin-cmoptions/assets/2982767/c71792ee-cc4f-46af-a841-be004692a93f)

**Comment by FelisDiligens** [comment]
I think, I found the cause: Setting the `Editor maximum width` under `Options` → `Appearance` to anything other than `0` seems to cause this issue.

![](https://github.com/FelisDiligens/joplin-plugin-cmoptions/assets/47528453/2c483790-e660-49ae-b221-fd74a37d5673)

**Comment by AZ2Tonez** [comment]
Ah - yes, I do have that set to 700.

**Comment by FelisDiligens** [comment]
I added a checkbox in v1.1.0 that should fix it:

![](https://github.com/FelisDiligens/joplin-plugin-cmoptions/assets/47528453/4f326d9b-9e0f-4761-97f5-eb42fe94f4ee)

It loads this stylesheet: [src/fix-linenumbers.css](https://github.com/FelisDiligens/joplin-plugin-cmoptions/blob/915ab469760dd8e97e9a5e4e54d8e34ef02f232f/src/fix-linenumbers.css)

Please update the plugin, then check the box in the settings and restart Joplin.
If it's not fixed, please tell me. I can reopen the issue.

**Comment by AZ2Tonez** [comment]
That fixes it, thank you!
